<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationCore">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\PresentationCore.dll</HintPath>
    </Reference>
    <Reference Include="WindowsBase">
      <HintPath>..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.20\WindowsBase.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
